import type { Profile, Project, SkillCategory, Zone, ZoneMeta } from './types';

export const profile: Profile = {
  name: 'Saatvik Choudhary',
  headline:
    'Chip architect & full-stack engineer — from custom AI-accelerator ASICs (Verilog/RTL) to production web, mobile, and data systems.',
  email: 'saatvik1213@gmail.com',
  linkedin: 'https://www.linkedin.com/in/saatvik-choudhary/',
  github: 'https://github.com/Vick1213',
  githubAlt: 'https://github.com/saatvik1213',
  booking:
    'https://calendar.google.com/calendar/appointments/schedules/AcZssZ2wAS0S2btEu6jxe6ptA0VAAEhBKVybDo4RgdL4dXZqMNufs7eY_K9thjV_coTIeglARHlw5vZR',
  languages: [
    'Verilog',
    'SystemVerilog',
    'Tcl',
    'Python',
    'TypeScript',
    'JavaScript',
    'Rust',
    'C++',
    'C#/ASP.NET',
    'Astro',
    'Ruby',
    'Jupyter',
    'PLpgSQL',
    'MDX',
    'Shell',
    'Makefile',
  ],
};

export const zones: ZoneMeta[] = [
  {
    id: 'silicon',
    label: 'Silicon',
    blurb: 'Custom AI-accelerator ASIC design — RTL, simulation, and synthesis flows.',
    accent: '#5eead4',
    origin: [-18, 0, 0],
  },
  {
    id: 'web',
    label: 'Web & Full-Stack',
    blurb: 'Production web and mobile applications across Next.js, React, and Python.',
    accent: '#818cf8',
    origin: [-6, 0, 0],
  },
  {
    id: 'client',
    label: 'Client & Product',
    blurb: 'Company and client sites, platforms, and data tooling shipped to production.',
    accent: '#f0abfc',
    origin: [6, 0, 0],
  },
  {
    id: 'ml',
    label: 'ML Roots',
    blurb: 'Earlier machine-learning, data, game, and coursework foundations (2022–2024).',
    accent: '#fbbf24',
    origin: [18, 0, 0],
  },
];

export const zoneById = Object.fromEntries(zones.map((z) => [z.id, z])) as Record<Zone, ZoneMeta>;

export const allProjects: Project[] = [
  {
    id: 'aitochip',
    name: 'AiToChip — Neural MAX & Neural 1 AI Inference Accelerators',
    tagline:
      'From-scratch design of two custom AI-inference accelerator ASICs (datacenter + edge) with full RTL, simulation, and synthesis flows.',
    description:
      'A two-tapeout AI-accelerator program. "Neural MAX" is an enterprise/datacenter chip: heterogeneous architecture with 128 hetero-slots (attention + expert tiles), ~720 mm2 planar die, 12x HBM3e stacks (14 TB/s), 600 W TDP, and a runtime-configurable firmware profile (per-model SRAM partitioning, precision, per-slot power gating) targeting MoE LLM inference (Qwen3-30B, Kimi K2). "Neural 1" is an ultra-compact 69.7 mm2 edge accelerator (4x HBM3e, 5.79 W). Includes a Python RTL generator (ChipSpec to Verilog), reference decoders, and a GPT-2 numerics regression suite.',
    zone: 'silicon',
    type: 'original',
    tile: true,
    featured: true,
    grid: [0, 0],
    start: '2026-03',
    lastActive: '2026-04',
    status: 'active',
    months: 2,
    primaryLanguage: 'Verilog',
    commits: 113,
    tech: [
      'Verilog',
      'SystemVerilog',
      'Python',
      'Rust',
      'Tcl (synthesis/PnR)',
      'Yosys',
      'Static Timing Analysis',
      'Makefile',
      'Shell',
    ],
    skills: [
      'Digital RTL / ASIC design',
      'AI accelerator architecture',
      'Memory-hierarchy & HBM design',
      'Quantization (INT8/INT4/FP8/MXFP4/NVFP4)',
      'Logic synthesis & timing closure',
      'LLM inference throughput modeling',
      'Generative RTL tooling (Python codegen)',
    ],
    bullets: [
      'Architected two custom AI-inference accelerator ASICs from scratch — a 720 mm2 datacenter chip (128 heterogeneous compute slots, 12x HBM3e, 600 W TDP) and a 69.7 mm2 edge chip — modeling 600 W-envelope throughput of 5,500-6,600 tok/s on a 30B-parameter MoE LLM.',
      'Built a Python RTL generator that compiles a chip specification into 7+ configuration-dependent Verilog modules, enabling one physical die to be re-targeted per model via firmware (SRAM partitioning, precision mode, per-slot power gating).',
      'Established a numerics CI gate with reference decoders and a GPT-2 regression suite to validate quantized kernels against floating-point baselines; passed Yosys hierarchy checks across 113 commits.',
      'Designed a runtime-configurable mixed-precision datapath (INT8 physical MACs with INT4/FP8/MXFP4/NVFP4 codes reserved) and a chiplet bridge with a round-robin K-of-N arbiter over UCIe PHY.',
    ],
    links: { repo: 'https://github.com/Vick1213/AiToChip' },
  },
  {
    id: 'productivityai',
    name: 'ProductivityAI',
    tagline: 'AI-powered productivity web application.',
    description:
      'A substantial Next.js/TypeScript AI productivity application developed over ~8 months (532 KB of TypeScript, 93 commits, ~20 MB repo). Deployed on Vercel. One of the most sustained original web projects in the portfolio.',
    zone: 'web',
    type: 'original',
    tile: true,
    featured: true,
    grid: [0, 0],
    start: '2025-05',
    lastActive: '2026-01',
    status: 'maintained',
    months: 8,
    primaryLanguage: 'TypeScript',
    commits: 93,
    tech: ['Next.js', 'TypeScript', 'React', 'Tailwind CSS', 'Vercel'],
    skills: ['Full-stack web development', 'AI feature integration', 'Long-running project maintenance'],
    bullets: [
      'Built and maintained an AI productivity web app in Next.js/TypeScript over 8 months and 93 commits, deployed continuously on Vercel.',
    ],
    links: { repo: 'https://github.com/Vick1213/productivityai', live: 'https://productivityai.pro' },
  },
  {
    id: 'platforms-starter-kit',
    name: 'MarketPlace — Multi-Tenant E-commerce Platform',
    tagline:
      'Production-ready multi-tenant marketplace with per-seller subdomains and role-based auth.',
    description:
      'A multi-tenant marketplace (Alibaba/Amazon-inspired) built on Next.js 15 with subdomain routing for sellers, role-based authentication (Admin/Seller/User), OAuth (Google/Apple/Credentials), a SHA-256-hashed secret admin subdomain, seller dashboards, and per-seller storefronts. Note: repo name references the Vercel "platforms" starter but the implementation is a custom marketplace.',
    zone: 'web',
    type: 'original',
    tile: true,
    featured: true,
    grid: [-1, 0],
    start: '2026-01',
    lastActive: '2026-02',
    status: 'completed',
    months: 1,
    primaryLanguage: 'TypeScript',
    commits: 63,
    tech: [
      'Next.js 15 (App Router, Turbopack)',
      'React 19',
      'NextAuth.js v5',
      'Upstash Redis',
      'Tailwind 4',
      'shadcn/ui',
      'TypeScript',
    ],
    skills: [
      'Multi-tenant architecture',
      'Subdomain routing',
      'Role-based access control',
      'OAuth / authentication',
      'Redis data modeling',
    ],
    bullets: [
      'Built a multi-tenant e-commerce marketplace on Next.js 15 with wildcard-subdomain routing, giving each seller an isolated storefront and the platform a SHA-256-hashed secret admin subdomain.',
      'Implemented role-based authentication (Admin/Seller/User) with NextAuth.js v5 and OAuth providers, backed by Upstash Redis for tenant data.',
    ],
    links: {
      repo: 'https://github.com/Vick1213/platforms-starter-kit',
      live: 'https://platforms-starter-kit-xi-rouge.vercel.app',
    },
  },
  {
    id: 'market-terminal',
    name: 'Market Terminal — Local-First Market-Intelligence Dashboard',
    tagline:
      'Private, free-data market-intelligence terminal: Next.js dashboard + FastAPI backend + local sentiment models, all running on the user’s machine.',
    description:
      'A local-first market-intelligence terminal (monorepo) wiring a Next.js 15 dashboard to a FastAPI backend over REST + WebSocket, with a configurable react-grid-layout panel grid and a live system panel. Backend runs an APScheduler-driven ingest layer (httpx/aiolimiter/tenacity/diskcache over free data sources) into DuckDB (time-series) and SQLite WAL (app state), with WebSocket fan-out to the UI. Sentiment is computed locally (FinBERT for bulk + a local LLM for aspect/brief). Shared OpenAPI-generated TS types tie the FastAPI schema to the frontend. Currently at "Phase 0" — a runnable end-to-end skeleton (REST + WS + scheduler + storage + ingest wired through).',
    zone: 'web',
    type: 'original',
    tile: true,
    featured: false,
    grid: [1, 0],
    start: '2026-06',
    lastActive: '2026-06',
    status: 'active',
    months: 1,
    primaryLanguage: 'Python',
    commits: 17,
    tech: [
      'Next.js 15',
      'TypeScript',
      'react-grid-layout',
      'TanStack Query',
      'Zustand',
      'FastAPI (Python)',
      'WebSocket',
      'APScheduler',
      'DuckDB',
      'SQLite (WAL)',
      'FinBERT',
      'local LLM',
      'uv / pnpm monorepo',
    ],
    skills: [
      'Full-stack development (Python + TypeScript)',
      'Real-time data (WebSocket fan-out)',
      'Time-series storage (DuckDB)',
      'Data ingestion / scheduling pipelines',
      'Local NLP / sentiment models (FinBERT, local LLM)',
      'OpenAPI type generation',
    ],
    bullets: [
      'Built a local-first market-intelligence terminal as a Next.js 15 + FastAPI monorepo, streaming live data to a configurable dashboard grid over REST and WebSocket with end-to-end OpenAPI-generated TypeScript types.',
      'Designed an APScheduler-driven ingestion layer (rate-limited httpx with retry/caching) persisting to DuckDB time-series + SQLite WAL, and computed market sentiment locally with FinBERT and a local LLM — no paid data feeds or cloud APIs.',
    ],
    links: { repo: 'https://github.com/Vick1213/market-terminal' },
  },
  {
    id: 'storyboardai',
    name: 'StoryBoard AI',
    tagline:
      'Cross-platform React Native app for managing story characters, personalities, and relationships.',
    description:
      'A React Native (Expo) app with a Node.js/Express + Prisma/PostgreSQL backend for writers and game designers. Features include a Big-Five personality system, backstory builder, relationship mapping (trust levels, outcomes), and story object tracking. Cross-platform across iOS, Android, and Web.',
    zone: 'web',
    type: 'original',
    tile: true,
    featured: false,
    grid: [-1, 1],
    start: '2026-01',
    lastActive: '2026-01',
    status: 'completed',
    months: 1,
    primaryLanguage: 'JavaScript',
    commits: 6,
    tech: [
      'React Native',
      'Expo',
      'React Navigation',
      'Node.js',
      'Express',
      'Prisma ORM',
      'PostgreSQL (Neon)',
    ],
    skills: ['Mobile development (cross-platform)', 'REST API design', 'Relational data modeling'],
    bullets: [
      'Developed a cross-platform (iOS/Android/Web) React Native app for character-driven storytelling, with a Node.js/Express + Prisma/PostgreSQL backend exposing a RESTful API for characters, relationships, and story objects.',
      'Designed a relational schema modeling Big-Five personality traits, backstories, and inter-character relationships with trust levels and outcomes.',
    ],
    links: { repo: 'https://github.com/Vick1213/StoryBoardAI' },
  },
  {
    id: 'storyboardai-aws',
    name: 'StoryboardAI — AWS-Native Rebuild',
    tagline:
      'Ground-up AWS-native rebuild of StoryboardAI: a multimodal, globally-synced creative environment where a story is a "project" co-authored by AI agents — all infrastructure defined in AWS CDK.',
    description:
      'A from-scratch, AWS-native re-architecture of the earlier StoryBoardAI app (see id="storyboardai"). The product model: a story is a project with a living "story bible" as the source of truth and persistent characters, co-authored by an AI that toggles between an autonomous agent and a steerable copilot across text, image, and audio. The core engineering bet is a context-assembly loop — slice the authoritative bible into context on every action and check generated output back against it for continuity/drift. Single TypeScript monorepo (Turborepo) with Next.js web + Expo mobile (later), all cloud infra in AWS CDK. HONESTY NOTE: greenfield / early-stage (7 commits) — at this point it is primarily a detailed architecture spec (docs/ARCHITECTURE.md) plus initial scaffolding, not a shipped app. Present it as cloud-architecture / system-design work, not a finished product.',
    zone: 'web',
    type: 'original',
    tile: true,
    featured: false,
    grid: [0, 1],
    start: '2026-05',
    lastActive: '2026-06',
    status: 'early',
    months: 1,
    primaryLanguage: 'TypeScript',
    commits: 7,
    tech: [
      'AWS CDK (TypeScript)',
      'AWS AppSync (GraphQL + sync)',
      'AWS Lambda',
      'DynamoDB',
      'Aurora Serverless v2 / pgvector',
      'Amazon Cognito',
      'Claude via Amazon Bedrock',
      'AWS Step Functions',
      'S3 + CloudFront',
      'Next.js',
      'Expo',
      'Turborepo',
    ],
    skills: [
      'AWS cloud architecture (CDK / IaC)',
      'Serverless (Lambda, AppSync, Step Functions)',
      'GraphQL + offline sync',
      'Vector search (pgvector / Aurora Serverless)',
      'LLM orchestration (Bedrock / Claude, agent + copilot modes)',
      'System design / context-assembly for continuity',
    ],
    bullets: [
      'Architected an AWS-native rebuild of an AI storytelling platform — AppSync GraphQL with offline sync, Lambda + Step Functions orchestration, DynamoDB + Aurora Serverless v2/pgvector, Cognito auth, and Claude via Amazon Bedrock — with all infrastructure defined in AWS CDK (TypeScript).',
      'Designed a context-assembly engine that treats a persistent "story bible" as the source of truth, slicing relevant state into each AI action and verifying generated output back against it to prevent narrative drift.',
    ],
    links: { repo: 'https://github.com/Vick1213/storyboardAINew' },
  },
  {
    id: 'all-leads-foc',
    name: 'All-Leads-from-FOC — Lead Data Pipeline',
    tagline: 'Python pipeline for aggregating and processing sales/lead data.',
    description:
      'A Python + HTML data project (~12 MB) for collecting and organizing lead data. Substantial dataset/processing footprint; private. (No README — inferred from name, language mix, and size.)',
    zone: 'web',
    type: 'original',
    tile: false,
    featured: false,
    start: '2025-12',
    lastActive: '2026-01',
    status: 'completed',
    months: 2,
    primaryLanguage: 'Python',
    commits: 15,
    tech: ['Python', 'HTML'],
    skills: ['Data processing / ETL', 'Web scraping', 'Lead generation tooling'],
    bullets: ['Built a Python data pipeline to aggregate and structure sales-lead data into reportable output.'],
    links: { repo: 'https://github.com/Vick1213/All-Leads-from-FOC' },
  },
  {
    id: 'socialscapescraper',
    name: 'SocialScape Scraper',
    tagline: 'Social-media data scraping tool with a Next.js frontend.',
    description:
      'A Next.js/TypeScript application for scraping and presenting social-media data, deployed on Vercel.',
    zone: 'web',
    type: 'original',
    tile: true,
    featured: false,
    grid: [1, 1],
    start: '2025-03',
    lastActive: '2025-05',
    status: 'completed',
    months: 2,
    primaryLanguage: 'TypeScript',
    commits: 21,
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    skills: ['Web scraping', 'Full-stack web development'],
    bullets: ['Built a social-media scraping tool with a Next.js/TypeScript interface, deployed on Vercel.'],
    links: {
      repo: 'https://github.com/Vick1213/socialscapescraper',
      live: 'https://socialscapescraper.vercel.app',
    },
  },
  {
    id: 'proposal-generator-ai',
    name: 'AI Proposal Generator',
    tagline: 'AI tool that generates business proposals.',
    description:
      'AI-driven proposal generation web app (JavaScript), deployed on Vercel. A v2 iteration of the earlier "proposal-generator" project.',
    zone: 'web',
    type: 'original',
    tile: true,
    featured: false,
    grid: [-1, 2],
    start: '2025-05',
    lastActive: '2025-05',
    status: 'completed',
    months: 1,
    primaryLanguage: 'JavaScript',
    commits: 5,
    tech: ['JavaScript', 'HTML/CSS', 'Vercel'],
    skills: ['LLM application development', 'Frontend development'],
    bullets: ['Built an AI proposal-generation web app that produces formatted business proposals from prompts.'],
    links: {
      repo: 'https://github.com/Vick1213/proposal-generator-ai',
      live: 'https://proposal-generator-ai.vercel.app',
    },
  },
  {
    id: 'proposal-generator',
    name: 'Proposal Generator (v1)',
    tagline: 'First iteration of the proposal-generation app.',
    description: 'Original version of the proposal generator; superseded by the AI variant.',
    zone: 'web',
    type: 'original',
    tile: false,
    featured: false,
    start: '2025-05',
    lastActive: '2025-05',
    status: 'completed',
    months: 1,
    primaryLanguage: 'JavaScript',
    commits: 7,
    tech: ['JavaScript', 'HTML/CSS'],
    skills: ['Frontend development'],
    bullets: ['Prototyped a proposal-generation web tool (later evolved into an AI-driven version).'],
    links: {
      repo: 'https://github.com/Vick1213/proposal-generator',
      live: 'https://proposal-generator-psi.vercel.app',
    },
  },
  {
    id: 'coffeeapp',
    name: 'CoffeeApp',
    tagline: 'React + TypeScript + Vite application.',
    description:
      'A React/TypeScript app scaffolded with Vite, deployed on Vercel. (Default README — purpose inferred from name.)',
    zone: 'web',
    type: 'original',
    tile: true,
    featured: false,
    grid: [0, 2],
    start: '2026-02',
    lastActive: '2026-02',
    status: 'completed',
    months: 1,
    primaryLanguage: 'TypeScript',
    commits: 13,
    tech: ['React', 'TypeScript', 'Vite'],
    skills: ['Frontend development'],
    bullets: ['Built a React/TypeScript single-page app with Vite, deployed on Vercel.'],
    links: { repo: 'https://github.com/Vick1213/CoffeeApp', live: 'https://coffee-app-eight-olive.vercel.app' },
  },
  {
    id: 'personalwebsite',
    name: 'Personal Website / Portfolio',
    tagline: 'Personal portfolio site.',
    description: 'A personal portfolio website built with Next.js/TypeScript, deployed on Vercel.',
    zone: 'web',
    type: 'original',
    tile: true,
    featured: false,
    grid: [1, 2],
    start: '2025-10',
    lastActive: '2026-01',
    status: 'maintained',
    months: 3,
    primaryLanguage: 'TypeScript',
    commits: 7,
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    skills: ['Frontend development', 'Personal branding'],
    bullets: ['Designed and deployed a personal portfolio site in Next.js/TypeScript.'],
    links: {
      repo: 'https://github.com/Vick1213/personalwebsite',
      live: 'https://personalwebsite-ten-eta.vercel.app',
    },
  },
  {
    id: 'inference1',
    name: 'Velocity Silicon — Company Website',
    tagline: 'Marketing/product site for Velocity Silicon (the AI-chip venture behind AiToChip).',
    description:
      'The public web presence for Velocity Silicon (the company commercializing the AiToChip accelerators). Scaffolded with the Base44 AI app builder and customized; deployed on Vercel.',
    zone: 'client',
    type: 'ai-builder',
    tile: true,
    featured: true,
    grid: [0, 0],
    start: '2026-03',
    lastActive: '2026-05',
    status: 'active',
    months: 2,
    primaryLanguage: 'JavaScript',
    commits: 58,
    tech: ['JavaScript', 'Vite', 'Base44', 'Vercel'],
    skills: ['Web development', 'AI app builders', 'Product marketing site'],
    bullets: ['Built and iterated (58 commits) the marketing site for an AI-chip venture, shipping continuously to Vercel.'],
    links: { repo: 'https://github.com/Vick1213/Inference1', live: 'https://inference1.vercel.app' },
  },
  {
    id: 'kensridge-base44-app',
    name: 'Kensridge App (Base44)',
    tagline: 'Web application for Kensridge Partners (capital-introduction advisory).',
    description:
      'A Base44-scaffolded application for Kensridge Partners, actively developed (94 commits). Most-iterated of the Kensridge web properties.',
    zone: 'client',
    type: 'ai-builder',
    tile: true,
    featured: false,
    grid: [-1, 0],
    start: '2026-03',
    lastActive: '2026-05',
    status: 'active',
    months: 2,
    primaryLanguage: 'JavaScript',
    commits: 94,
    tech: ['JavaScript', 'TypeScript', 'Base44'],
    skills: ['Web development', 'AI app builders', 'Client delivery'],
    bullets: ['Delivered a client web application (94 commits) for a capital-introduction advisory firm.'],
    links: { repo: 'https://github.com/Vick1213/kensridge-base44-app' },
  },
  {
    id: 'kensridge-data-platform',
    name: 'Kensridge Data Platform',
    tagline: 'Data platform combining a TypeScript app with Python processing.',
    description:
      'A data platform (TypeScript frontend/app + Python backend/processing, ~14 MB). Single commit but large footprint — likely a bulk initial push of an established codebase. Verify maturity before featuring prominently.',
    zone: 'client',
    type: 'original',
    tile: true,
    featured: false,
    grid: [1, 0],
    start: '2026-04',
    lastActive: '2026-04',
    status: 'early',
    months: 1,
    primaryLanguage: 'TypeScript',
    commits: 1,
    tech: ['TypeScript', 'Python'],
    skills: ['Data platform engineering', 'Full-stack development'],
    bullets: ['Built a data platform pairing a TypeScript application layer with Python data processing.'],
    links: { repo: 'https://github.com/Vick1213/KensridgeDataPlatform' },
  },
  {
    id: 'kensridge-partners',
    name: 'Kensridge Partners — Advisory Website',
    tagline: 'Boutique capital-introduction advisory marketing site.',
    description:
      'Marketing website for Kensridge Partners, built with Next.js/TypeScript and MDX content.',
    zone: 'client',
    type: 'original',
    tile: true,
    featured: false,
    grid: [-1, 1],
    start: '2026-03',
    lastActive: '2026-03',
    status: 'completed',
    months: 1,
    primaryLanguage: 'TypeScript',
    commits: 10,
    tech: ['Next.js', 'TypeScript', 'MDX'],
    skills: ['Frontend development', 'Content-driven sites (MDX)'],
    bullets: ["Built a boutique advisory firm's marketing website in Next.js/TypeScript with MDX-driven content."],
    links: { repo: 'https://github.com/Vick1213/kensridge-partners' },
  },
  {
    id: 'kensridge-app',
    name: 'Kensridge App (early)',
    tagline: 'Early JavaScript version of the Kensridge web app.',
    description: 'An early/public iteration of the Kensridge application, later superseded by the Base44 build.',
    zone: 'client',
    type: 'original',
    tile: false,
    featured: false,
    start: '2026-03',
    lastActive: '2026-03',
    status: 'superseded',
    months: 1,
    primaryLanguage: 'JavaScript',
    commits: 3,
    tech: ['JavaScript'],
    skills: ['Frontend development'],
    bullets: ['Prototyped an early version of a client web app (superseded by a later build).'],
    links: { repo: 'https://github.com/Vick1213/kensridge-app' },
  },
  {
    id: 'klusterai-website',
    name: 'Kluster AI Website',
    tagline: 'Marketing website (single-commit landing build).',
    description: 'A small Next.js/TypeScript marketing site, deployed on Vercel.',
    zone: 'client',
    type: 'original',
    tile: true,
    featured: false,
    grid: [0, 1],
    start: '2025-03',
    lastActive: '2025-03',
    status: 'completed',
    months: 1,
    primaryLanguage: 'TypeScript',
    commits: 1,
    tech: ['Next.js', 'TypeScript'],
    skills: ['Frontend development'],
    bullets: ['Built and deployed a marketing landing site in Next.js.'],
    links: { repo: 'https://github.com/Vick1213/KlusterAiWebsite', live: 'https://kluster-ai-website.vercel.app' },
  },
  {
    id: 'hr_chatbot',
    name: 'HR Chatbot',
    tagline: 'HR-domain AI chat app built on the open-source Chatbot UI.',
    description:
      'An HR-focused chatbot adapted from the open-source "Chatbot UI" (mckaywrigley), with a Supabase/PostgreSQL backend (PLpgSQL). Deployed on Vercel. Customization was light (2 commits) — present as a deployment/integration project, not from-scratch.',
    zone: 'web',
    type: 'template-based',
    tile: false,
    featured: false,
    start: '2025-06',
    lastActive: '2025-06',
    status: 'completed',
    months: 1,
    primaryLanguage: 'TypeScript',
    commits: 2,
    tech: ['TypeScript', 'Next.js', 'Supabase', 'PostgreSQL / PLpgSQL'],
    skills: ['LLM chatbot integration', 'Supabase / Postgres', 'Deploying open-source projects'],
    bullets: ['Adapted and deployed an open-source LLM chat UI into an HR-domain assistant backed by Supabase/PostgreSQL.'],
    links: { repo: 'https://github.com/Vick1213/hr_chatbot', live: 'https://hrchatbot.vercel.app' },
  },
  {
    id: 'quantumnreach',
    name: 'QuantumnReach — Outreach Dashboard',
    tagline: 'Outreach/CRM dashboard built on the TailAdmin Next.js template.',
    description:
      'A dashboard application started from the open-source TailAdmin (Next.js 14 + Tailwind) template and customized for outreach use, deployed on Vercel.',
    zone: 'web',
    type: 'template-based',
    tile: false,
    featured: false,
    start: '2025-02',
    lastActive: '2025-02',
    status: 'completed',
    months: 1,
    primaryLanguage: 'TypeScript',
    commits: 5,
    tech: ['Next.js 14', 'React 18', 'TypeScript', 'Tailwind CSS'],
    skills: ['Dashboard / admin UI', 'Template customization'],
    bullets: ['Customized a Next.js admin-dashboard template into an outreach tool and deployed it on Vercel.'],
    links: { repo: 'https://github.com/Vick1213/QuantumnReach', live: 'https://quantumn-reach.vercel.app' },
  },
  {
    id: 'odyssey',
    name: 'Odyssey — Astro Marketing Site',
    tagline: 'Business/startup marketing site built on the Astro Odyssey theme.',
    description:
      'A marketing website built on the open-source "Odyssey" Astro theme (blog, landing pages, contact forms, theme switcher). 70 commits of customization; achieves strong Lighthouse performance via Astro. Deployed on Vercel.',
    zone: 'web',
    type: 'template-based',
    tile: false,
    featured: false,
    start: '2024-11',
    lastActive: '2025-01',
    status: 'completed',
    months: 2,
    primaryLanguage: 'Astro',
    commits: 70,
    tech: ['Astro', 'TypeScript', 'MDX', 'CSS', 'Nix'],
    skills: ['Astro / static-site performance', 'SEO best practices', 'Theme customization'],
    bullets: ['Customized an Astro-based marketing theme (blog, landing pages, contact forms) for a startup site, optimizing for Lighthouse performance and SEO.'],
    links: { repo: 'https://github.com/Vick1213/odyssey', live: 'https://odyssey-rust.vercel.app' },
  },
  {
    id: 'router',
    name: 'Router.so — Self-Hosted Form Backend',
    tagline: 'Self-hosted deployment of the open-source router.so form/lead-routing backend.',
    description:
      'A self-hosted instance of router.so (headless form handling and lead routing). The 269-commit count largely reflects upstream history — treat this as a deployment/operations project, NOT 269 commits of original authorship. Useful for demonstrating self-hosting of a TypeScript + Postgres + Docker stack.',
    zone: 'web',
    type: 'fork',
    tile: false,
    featured: false,
    start: '2025-02',
    lastActive: '2025-02',
    status: 'completed',
    months: 1,
    primaryLanguage: 'TypeScript',
    commits: 269,
    tech: ['TypeScript', 'Next.js', 'PostgreSQL', 'Docker', 'Resend'],
    skills: ['Self-hosting open-source apps', 'Docker deployment', 'PostgreSQL ops'],
    bullets: ['Self-hosted an open-source form/lead-routing backend (Next.js + PostgreSQL + Docker), configuring Resend email and Vercel Postgres.'],
    links: { repo: 'https://github.com/Vick1213/router', live: 'https://router.so' },
  },
  {
    id: 'final-project-data',
    name: 'Data Science Final Project',
    tagline: 'Jupyter/Python data-analysis final project.',
    description:
      'A data-science course final project (Jupyter notebooks + Python, ~3.4 MB of analysis/dev data).',
    zone: 'ml',
    type: 'coursework',
    tile: false,
    featured: false,
    start: '2025-12',
    lastActive: '2025-12',
    status: 'completed',
    months: 1,
    primaryLanguage: 'Jupyter Notebook',
    commits: 13,
    tech: ['Python', 'Jupyter', 'Pandas (inferred)'],
    skills: ['Data analysis', 'Notebook-based exploration'],
    bullets: ['Completed a data-science final project analyzing a real dataset in Python/Jupyter.'],
    links: { repo: 'https://github.com/Vick1213/final_project_and_dev_data' },
  },
  {
    id: 'assignment4-services',
    name: 'ASP.NET Web Services (Assignment 4)',
    tagline: 'C#/ASP.NET web-services coursework.',
    description: 'University assignment building web services in C#/ASP.NET with a JS frontend.',
    zone: 'ml',
    type: 'coursework',
    tile: false,
    featured: false,
    start: '2025-04',
    lastActive: '2025-04',
    status: 'completed',
    months: 1,
    primaryLanguage: 'JavaScript',
    commits: 2,
    tech: ['C#', 'ASP.NET', 'JavaScript'],
    skills: ['C# / ASP.NET', 'Web services'],
    bullets: ['Built C#/ASP.NET web services as part of a distributed-software-development course.'],
    links: { repo: 'https://github.com/Vick1213/Assignment4.services' },
  },
  {
    id: 'cse445xml',
    name: 'CSE445 XML Assignment',
    tagline: 'XML / web-services coursework (CSE445).',
    description:
      'A small XML-focused assignment for ASU CSE445 (Distributed Software Development) — XML schemas/documents.',
    zone: 'ml',
    type: 'coursework',
    tile: false,
    featured: false,
    start: '2025-04',
    lastActive: '2025-04',
    status: 'completed',
    months: 1,
    primaryLanguage: 'XML',
    commits: 4,
    tech: ['XML', 'XSD/XSLT (inferred)'],
    skills: ['XML schema design'],
    bullets: ['Completed XML schema/validation coursework in CSE445.'],
    links: { repo: 'https://github.com/Vick1213/CSE445XML' },
  },
  {
    id: 'provided-code',
    name: 'C++ Coursework (provided_code)',
    tagline: 'C++ data-structures/algorithms assignments.',
    description: 'C++ coursework built on instructor-provided starter code and sample tests.',
    zone: 'ml',
    type: 'coursework',
    tile: false,
    featured: false,
    start: '2025-02',
    lastActive: '2025-02',
    status: 'completed',
    months: 1,
    primaryLanguage: 'C++',
    commits: 10,
    tech: ['C++', 'Shell'],
    skills: ['C++ programming', 'Data structures & algorithms'],
    bullets: ['Implemented C++ data-structures/algorithms assignments against provided test suites.'],
    links: { repo: 'https://github.com/Vick1213/provided_code' },
  },
  {
    id: 'provided-code-tests',
    name: 'C++ Coursework (provided_code_and_sample_tests)',
    tagline: 'Additional C++ assignment with sample tests.',
    description: 'A second C++ assignment repository with provided code and sample tests (Makefile-based).',
    zone: 'ml',
    type: 'coursework',
    tile: false,
    featured: false,
    start: '2025-03',
    lastActive: '2025-03',
    status: 'completed',
    months: 1,
    primaryLanguage: 'C++',
    commits: 1,
    tech: ['C++', 'Makefile', 'Shell'],
    skills: ['C++ programming'],
    bullets: ['Completed a C++ assignment using a Makefile build and provided sample tests.'],
    links: { repo: 'https://github.com/Vick1213/provided_code_and_sample_tests' },
  },
  {
    id: 'powergrader',
    name: 'PowerGrader — AI Automated Grading (SODA Hackathon)',
    tagline: 'Hackathon web app that auto-grades written student assignments, built by a 4-person team.',
    description:
      'Built at the SODA Hackathon (track: scaling/accessibility in education) with team "SSGA" (4 members). PowerGrader is a web application that provides automated grading for written assignment submissions on online education platforms — filling a gap left by tools that only grade multiple-choice or embedded-code questions. Next.js frontend, Flask (Python) backend, and Firebase. Includes a recorded UI demo and a project presentation. Repo has an external fork.',
    zone: 'ml',
    type: 'original',
    tile: true,
    featured: true,
    grid: [0, 0],
    start: '2024-10',
    lastActive: '2024-10',
    status: 'completed',
    months: 1,
    primaryLanguage: 'JavaScript',
    commits: 65,
    tech: ['Next.js', 'React', 'Flask (Python)', 'Firebase', 'Tailwind CSS'],
    skills: [
      'Full-stack development',
      'NLP / automated grading',
      'Rapid prototyping (hackathon)',
      'Team collaboration',
      'Python/Flask APIs',
    ],
    bullets: [
      'Built PowerGrader at the SODA hackathon with a 4-person team: a Next.js + Flask + Firebase web app that automatically grades written (free-text) student assignments, addressing a gap in online-learning tools that only grade multiple-choice questions.',
      'Delivered a working end-to-end demo (student UI + grading backend) within the hackathon timeframe; project earned an external fork on GitHub.',
    ],
    links: {
      repo: 'https://github.com/saatvik1213/powergradernew',
      presentation: 'https://gamma.app/docs/PowerGrader-29m054unrf8q5xa',
      demo: 'https://youtu.be/aIbw28HNHtk',
    },
  },
  {
    id: 'crypto-news-sentiment',
    name: 'Crypto News Sentiment Model (Doc2Vec + LSTM)',
    tagline: 'NLP model that scores crypto-market sentiment from scraped news.',
    description:
      'A sentiment-analysis pipeline for cryptocurrency news: scrapes articles via public APIs, embeds text with Doc2Vec, and feeds the embeddings into an LSTM to produce a sentiment signal. Implemented in Jupyter/Python.',
    zone: 'ml',
    type: 'original',
    tile: true,
    featured: false,
    grid: [-1, 0],
    start: '2024-09',
    lastActive: '2024-09',
    status: 'completed',
    months: 1,
    primaryLanguage: 'Jupyter Notebook',
    commits: 3,
    tech: ['Python', 'Jupyter', 'Doc2Vec (Gensim)', 'LSTM (Keras/TensorFlow)', 'News APIs'],
    skills: ['NLP / text embeddings', 'Recurrent neural networks (LSTM)', 'Data scraping', 'Financial-data modeling'],
    bullets: ['Built a crypto-news sentiment model that scrapes articles via public APIs, embeds them with Doc2Vec, and classifies market sentiment with an LSTM.'],
    links: { repo: 'https://github.com/saatvik1213/Crypto_News_sentiment' },
  },
  {
    id: 'asl-detector',
    name: 'Sign Language (ASL) Detector',
    tagline: 'Deep-learning model that translates ASL video into text.',
    description:
      'A deep-learning project to read American Sign Language from video and translate it into text, aimed at improving accessibility/communication. Implemented in Jupyter/Python (early-stage prototype).',
    zone: 'ml',
    type: 'original',
    tile: true,
    featured: false,
    grid: [1, 0],
    start: '2024-09',
    lastActive: '2024-09',
    status: 'prototype',
    months: 1,
    primaryLanguage: 'Jupyter Notebook',
    commits: 4,
    tech: ['Python', 'Jupyter', 'Deep learning (CNN/sequence models)', 'Computer vision'],
    skills: ['Computer vision', 'Video/sequence modeling', 'Accessibility-focused ML'],
    bullets: ['Prototyped a deep-learning model to translate American Sign Language video into text, targeting accessibility for the hearing-impaired.'],
    links: { repo: 'https://github.com/saatvik1213/SignLanguage-ASL-Detector' },
  },
  {
    id: 'cnn-classifier',
    name: 'Computer Vision Image Classifier (CNN)',
    tagline: 'Convolutional neural network for image classification.',
    description:
      'A Python CNN built to classify images — an early hands-on deep-learning / computer-vision project.',
    zone: 'ml',
    type: 'original',
    tile: true,
    featured: false,
    grid: [-1, 1],
    start: '2022-11',
    lastActive: '2022-12',
    status: 'completed',
    months: 1,
    primaryLanguage: 'Python',
    commits: 3,
    tech: ['Python', 'CNN (Keras/TensorFlow)', 'Computer vision'],
    skills: ['Convolutional neural networks', 'Image classification'],
    bullets: ['Implemented a convolutional neural network in Python for image classification.'],
    links: { repo: 'https://github.com/saatvik1213/Computer-vision-classifiern-using-cnn' },
  },
  {
    id: 'epic-store-fps',
    name: 'Epic Store — FPS Co-Op Game (Unreal Engine)',
    tagline: 'First-person-shooter co-op game built in Unreal Engine 5.3.',
    description:
      'A first-person-shooter cooperative game built on Unreal Engine 5.3 (C++/C#, ~27 MB). Single commit reflects a bulk push of the project. Demonstrates real-time 3D game development and engine work.',
    zone: 'ml',
    type: 'original',
    tile: true,
    featured: false,
    grid: [0, 1],
    start: '2023-10',
    lastActive: '2023-10',
    status: 'completed',
    months: 1,
    primaryLanguage: 'C++',
    commits: 1,
    tech: ['Unreal Engine 5.3', 'C++', 'C#', 'Game development'],
    skills: ['Game development', 'Unreal Engine', 'C++ / real-time systems'],
    bullets: ['Built a cooperative first-person-shooter game in Unreal Engine 5.3 using C++.'],
    links: { repo: 'https://github.com/saatvik1213/Epic-Store--FPS-CoOp-' },
  },
  {
    id: 'demoapp-flutter',
    name: 'Flutter / Dart Cross-Platform App (learning)',
    tagline: 'Cross-platform mobile app built while learning Flutter/Dart.',
    description:
      'A cross-platform app project built while learning Dart and Flutter (large disk size is mostly platform build artifacts). Use to show breadth of mobile frameworks (Flutter alongside React Native), not as a flagship project.',
    zone: 'ml',
    type: 'coursework',
    tile: false,
    featured: false,
    start: '2022-12',
    lastActive: '2022-12',
    status: 'learning',
    months: 1,
    primaryLanguage: 'Dart',
    commits: 2,
    tech: ['Flutter', 'Dart', 'Android (Kotlin/Java)', 'iOS (Swift/Obj-C)'],
    skills: ['Flutter / Dart', 'Cross-platform mobile'],
    bullets: ['Learned and built a cross-platform mobile app with Flutter/Dart.'],
    links: { repo: 'https://github.com/saatvik1213/DemoAPP' },
  },
];

export const projects: Project[] = allProjects.filter((p) => p.tile);
export const resumeProjects: Project[] = allProjects;

export interface ExternalCollection {
  id: string;
  name: string;
  tagline: string;
  url: string;
  description: string;
  skills: string[];
}

export const externalCollections: ExternalCollection[] = [
  {
    id: 'ml-notebooks-drive',
    name: 'Machine-Learning Model Notebooks',
    tagline: 'A large personal collection of Python notebooks covering many different machine-learning models.',
    url: 'https://drive.google.com/drive/u/1/folders/1b2i9qt2KYFspeNr6T9EJcP03GwqwGVwE',
    description:
      'A Google Drive folder containing many Python/Jupyter notebooks implementing a wide range of machine-learning models and experiments. Breadth is the point here — the collection is large and intentionally not catalogued item-by-item. Treat it as supporting evidence of sustained, broad ML experimentation.',
    skills: ['Machine learning (broad)', 'Python / Jupyter', 'Model experimentation'],
  },
];

export const skillCategories: SkillCategory[] = [
  {
    name: 'Hardware / Chip Design',
    skills: [
      { label: 'Digital RTL design (Verilog / SystemVerilog)', level: 'advanced' },
      { label: 'AI accelerator / ML inference architecture', level: 'advanced' },
      { label: 'Logic synthesis (Yosys)', level: 'intermediate' },
      { label: 'Static Timing Analysis (STA)', level: 'intermediate' },
      { label: 'Physical design / floorplanning (Tcl flows)', level: 'intermediate' },
      { label: 'Memory hierarchy design (HBM3e, SRAM partitioning)', level: 'intermediate' },
      { label: 'Quantization (INT8/INT4/FP8/MXFP4) for inference', level: 'intermediate' },
    ],
  },
  {
    name: 'Languages',
    skills: [
      { label: 'TypeScript', level: 'advanced' },
      { label: 'JavaScript', level: 'advanced' },
      { label: 'Python', level: 'advanced' },
      { label: 'Verilog', level: 'advanced' },
      { label: 'C++', level: 'intermediate' },
      { label: 'Rust', level: 'intermediate' },
      { label: 'C# / ASP.NET', level: 'intermediate' },
      { label: 'SQL (PostgreSQL, PLpgSQL)', level: 'intermediate' },
    ],
  },
  {
    name: 'Web / Frontend',
    skills: [
      { label: 'Next.js (App Router, 14/15)', level: 'advanced' },
      { label: 'React (18/19)', level: 'advanced' },
      { label: 'Tailwind CSS', level: 'advanced' },
      { label: 'shadcn/ui', level: 'intermediate' },
      { label: 'Astro', level: 'intermediate' },
      { label: 'Vite', level: 'intermediate' },
    ],
  },
  {
    name: 'Backend / Data',
    skills: [
      { label: 'Node.js / Express', level: 'advanced' },
      { label: 'Prisma ORM', level: 'advanced' },
      { label: 'PostgreSQL (Neon, Supabase)', level: 'advanced' },
      { label: 'Redis (Upstash)', level: 'intermediate' },
      { label: 'NextAuth.js v5 (OAuth, RBAC)', level: 'intermediate' },
      { label: 'Multi-tenant / subdomain architecture', level: 'intermediate' },
      { label: 'Web scraping / lead-data pipelines', level: 'intermediate' },
      { label: 'Data analysis (Pandas, Jupyter)', level: 'intermediate' },
    ],
  },
  {
    name: 'Mobile',
    skills: [{ label: 'React Native (Expo, cross-platform iOS/Android/Web)', level: 'intermediate' }],
  },
  {
    name: 'AI / LLM',
    skills: [
      { label: 'LLM application development (chatbots, agents)', level: 'advanced' },
      { label: 'LLM inference serving / throughput modeling', level: 'intermediate' },
      { label: 'AI app builders (Base44)', level: 'intermediate' },
    ],
  },
  {
    name: 'Cloud / AWS',
    skills: [
      { label: 'AWS CDK (infrastructure as code, TypeScript)', level: 'intermediate' },
      { label: 'Serverless (Lambda, AppSync, Step Functions)', level: 'intermediate' },
      { label: 'DynamoDB + Aurora Serverless v2 / pgvector', level: 'intermediate' },
      { label: 'Cognito (auth)', level: 'intermediate' },
      { label: 'Amazon Bedrock (Claude) for LLM orchestration', level: 'intermediate' },
      { label: 'S3 + CloudFront', level: 'intermediate' },
    ],
  },
  {
    name: 'DevOps / Tooling',
    skills: [
      { label: 'Git / GitHub', level: 'advanced' },
      { label: 'Vercel deployment', level: 'advanced' },
      { label: 'Docker', level: 'intermediate' },
      { label: 'CI gates / regression test suites', level: 'intermediate' },
      { label: 'Shell scripting, Makefiles', level: 'intermediate' },
    ],
  },
];
